language: perl

addons:
  apt:
    packages:
      - tcsh
      - zsh
      - ksh
      - csh
      - fish

install:
  - bash .travis-install-system.sh
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - cpanm -n Shell::Guess
  - cpanm -n Test::CPAN::Changes Test::EOL Test::Fixme Test::NoTabs Test::Pod::Spelling::CommonMistakes Test::Spelling Test::Strict Test::Version || true

script: HARNESS_IS_VERBOSE=1 prove -lvr t xt

perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

script: dzil test -v

sudo: false

env:
  - PATH=$HOME/travislocal/bin:$PATH
